# Generated by Django 3.0 on 2023-11-07 03:25

from django.db import migrations
from profiles.models import Profile as OldProfile
from profiles.models import Profile

def copy_data_from_old_to_new(apps, schema_editor):
    for old_profile in OldProfile.objects.all():
        Profile.objects.create(
            user=old_profile.user,
            favorite_city=old_profile.favorite_city,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),  # Previous migration file for the profiles app
    ]

    operations = [
        migrations.RunPython(copy_data_from_old_to_new),
    ]

