# Generated by Django 3.0 on 2023-11-07 03:54

from django.db import migrations

def delete_old_tables(apps, schema_editor):
    OldProfile = apps.get_model('oc_lettings_site', 'Profile')
    OldProfile.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20231107_0425'),  # Previous migration file for the profiles app
    ]

    operations = [
        migrations.RunPython(delete_old_tables),
    ]

