# Generated by Django 3.0 on 2023-11-07 03:25

from django.db import migrations
from lettings.models import Address as OldAddress, Letting as OldLetting
from lettings.models import Address, Letting

def copy_data_from_old_to_new(apps, schema_editor):
    for old_address in OldAddress.objects.all():
        Address.objects.create(
            number=old_address.number,
            street=old_address.street,
            city=old_address.city,
            state=old_address.state,
            zip_code=old_address.zip_code,
            country_iso_code=old_address.country_iso_code,
        )
    
    for old_letting in OldLetting.objects.all():
        new_address = Address.objects.get(number=old_letting.address.number)
        Letting.objects.create(
            title=old_letting.title,
            address=new_address,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),  # Previous migration file for the lettings app
    ]

    operations = [
        migrations.RunPython(copy_data_from_old_to_new),
    ]

