# Generated by Django 4.2.7 on 2023-11-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0003_auto_20231124_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='letting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
