# Generated by Django 3.0 on 2023-11-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0003_auto_20231107_0444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
    ]
