name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
       
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Build Docker image
      run: |
        IMAGE_TAG=$(git rev-parse --short=7 HEAD)  # Get the short commit hash
        docker build -t azer7777/project-13:$IMAGE_TAG .
        docker tag azer7777/project-13:$IMAGE_TAG azer7777/project-13:latest
        echo $dckr_pat_Hxjqf0zvMOm3p__3x_5boJhzLbQ | docker login -u $azer7777 --password-stdin
        docker push $azer7777/project-13:$IMAGE_TAG
        docker push $azer7777/project-13:latest

    - name: Log in to Docker Hub
      run: echo $dckr_pat_Hxjqf0zvMOm3p__3x_5boJhzLbQ | docker login -u $azer7777 --password-stdin


    - name: Push Docker image to Docker Hub
      run: docker push azer7777/project-13:$IMAGE_TAG && docker push azer7777/project-13:latest

    - name: Run CI script
      run: bash ci_script.sh
