name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Build Docker image
        run: docker build -t $DOCKER_USERNAME/project-13:${{ github.sha }} .
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Push Docker image
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push $DOCKER_USERNAME/project-13:${{ github.sha }}
          docker push $DOCKER_USERNAME/project-13:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Run CI script
        run: bash ci_script.sh
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Render
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Deploy
        run: |
          curl -X GET $DEPLOY_HOOK
        env:
          DEPLOY_HOOK: ${{ secrets.DEPLOY_HOOK }}

